name: 'redocly-cli-github-action'
description: 'Use Redocly CLI and OpenAPI Specifications (OAS) to make API docs, convert YAML & JSON, bundle, lint, join specs and more.'
author: 'Sebastian Hesse <info@sebastianhesse.de>, kefasjw, fluximus-prime'
branding:
  icon: 'book'
  color: 'green'
inputs:
  args:
    description: 'The arguments to pass over to Redocly CLI'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}
