name: test-deploy

# Run on each push to master
on:
  push:
    branches: [ master ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing Private Usage
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Redocly CLI Test
        uses: ./ # Uses an action in the root directory
        with:
          args: 'build-docs test/petstore.yml --output ./petstore.html'

      - name: check result
        run: |
          ls -al
          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)

  test_job_2:
    runs-on: ubuntu-latest
    name: Testing Public Usage
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # use the public name of the action
      - name: Redocly CLI Test
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'build-docs test/petstore.yml --output ./petstore.html'

      - name: check result
        run: |
          ls -al
          test -f petstore.html || (echo "Missing petstore.html from previous step." && exit 1)
